services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Supseven\RedirectsUpdater\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  querybuilder.redirect:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory: [ '@TYPO3\CMS\Core\Database\ConnectionPool', 'getQueryBuilderForTable' ]
    arguments: [ 'sys_redirect' ]

  Supseven\RedirectsUpdater\Command\ReplaceSourceHostCommand:
    tags:
      - name: console.command
        command: 'typo3-redirects-updater:replace-source-host'
        description: 'Replace existing source host with a new source host value'
    arguments:
      $redirectQuery: '@querybuilder.redirect'
